version: "3.9"

services:
  crawling-server:
    build: .
    container_name: transnews-crawling-server
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped